version: "3.9"
services:
  ipv64-updater:
    image: XXX
    container_name: ipv64
    restart: unless-stopped
    environment:
      - "DOMAIN=deine-domain.ipv64.net"
      - "DOMAIN_KEY=1234567890abcdefghijklmn"
      # - "PRAEFIX=ddns"                      # optional
      # - "TZ=Europe/Berlin"                  # optional
      # - "CRON=*/5 * * * *"                  # optional
      # - "NTFY=https://ntfy.sh/mytopic"      # optional