version: "3.9"
services:
  ipv64-updater:
    image: r600/ipv64-updater:latest
    container_name: ipv64
    restart: unless-stopped
    environment:
      - "DOMAIN=domain.ipv64.net"
      - "TOKEN=1234567890abcdefghijklmn"
      - "RECORD_TYPE=A"
      # - "PREFIX=ddns"                      # optional
      # - "TZ=Europe/Berlin"                  # optional
      # - "CRON=*/5 * * * *"                  # optional
      # - "NTFY=https://ntfy.sh/mytopic"      # optional