version: "3.9"
services:
  ipv64-updater:
    image: r600/ipv64-updater:latest
    container_name: ipv64
    restart: unless-stopped
    environment:
      - "DOMAIN=domain.ipv64.net"
      - "TOKEN=1234567890abcdefghijklmn"
      # - "RECORD_TYPE=A"                                             # optional, standard "RECORD_TYPE=A"
      # - "PREFIX=ddns"                                               # optional, standard "PREFIX=None"
      # - "TZ=Europe/Berlin"                                          # optional, standard "TZ=Europe/Berlin"
      # - "CRON=*/5 * * * *"                                          # optional, standard "CRON=*/5 * * * *"
      # - "CHECK_RECORD=False"                                        # optional, True = check the dns record for set ip and only update if required, False = update dns record in every run, standard True
      # - "NTFY=https://ntfy.sh/mytopic"                              # optional, standard "NTFY=None"
      # - "DISCORD=https://discord.com/api/webhooks/121XXX"           # optional discord webhook, standard "DISCROD=None"